In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [3]:
a[-1]

np.int64(4)

In [4]:
b=np.array([1,2,3,4,5,6,7,8,9])
b[0:9]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
b=np.array([1,2,3,4,5,6,7,8,9])
b[-1:5]

array([], dtype=int64)

In [6]:
c=b.copy()
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
d=b.view()
d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
b[0]=12
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
d

array([12,  2,  3,  4,  5,  6,  7,  8,  9])

In [10]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
b=a.reshape(4,3)
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [12]:
c=np.array([13,14,15])
d=np.concatenate((a,c))

In [13]:
np.array_split(d,2)

[array([1, 2, 3, 4, 5, 6, 7, 8]), array([ 9, 10, 11, 12, 13, 14, 15])]

In [14]:
np.where(d==4)

(array([3]),)

In [15]:
np.where(d%2==0)

(array([ 1,  3,  5,  7,  9, 11, 13]),)

In [16]:
c=np.array([3,4,2,10,5])
np.sort(c)

array([ 2,  3,  4,  5, 10])

In [17]:
c=np.array([[2,3,1,6],[5,1,2,4]])
np.sort(c)

array([[1, 2, 3, 6],
       [1, 2, 4, 5]])

In [18]:
c=np.array(['apple','orange','banana','mango'])
np.sort(c)

array(['apple', 'banana', 'mango', 'orange'], dtype='<U6')

In [19]:
np.random.randint(100)

36

In [20]:
np.random.rand(10)

array([0.27546826, 0.43922247, 0.64577773, 0.05357484, 0.77288603,
       0.46353266, 0.55170078, 0.314369  , 0.29495032, 0.22049479])

In [21]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [22]:
np.ones(2)

array([1., 1.])

In [23]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2,5))